export const GET_USER_LIST = 'GET_USER_LIST';
export const USER_LIST = 'USER_LIST';

export const SUBMIT_MESSAGE = 'SUBMIT_MESSAGE';
export const USER_CONVERSATIONS = 'USER_CONVERSATIONS';
export const SINGLE_CONVERSIONS = 'SINGLE_CONVERSIONS';
